"use strict";
exports.__esModule = true;
exports.SECRET_JITSI_KEY = exports.JITSI_ISS = exports.JITSI_URL = exports.CPU_OVERHEAT_THRESHOLD = exports.ALLOW_ARTILLERY = exports.GROUP_RADIUS = exports.GRPC_PORT = exports.HTTP_PORT = exports.ADMIN_API_TOKEN = exports.ADMIN_API_URL = exports.MINIMUM_DISTANCE = exports.TURN_STATIC_AUTH_SECRET = exports.SOCKET_IDLE_TIMER = void 0;
var MINIMUM_DISTANCE = process.env.MINIMUM_DISTANCE ? Number(process.env.MINIMUM_DISTANCE) : 64;
exports.MINIMUM_DISTANCE = MINIMUM_DISTANCE;
var GROUP_RADIUS = process.env.GROUP_RADIUS ? Number(process.env.GROUP_RADIUS) : 48;
exports.GROUP_RADIUS = GROUP_RADIUS;
var ALLOW_ARTILLERY = process.env.ALLOW_ARTILLERY ? process.env.ALLOW_ARTILLERY == 'true' : false;
exports.ALLOW_ARTILLERY = ALLOW_ARTILLERY;
var ADMIN_API_URL = process.env.ADMIN_API_URL || '';
exports.ADMIN_API_URL = ADMIN_API_URL;
var ADMIN_API_TOKEN = process.env.ADMIN_API_TOKEN || 'myapitoken';
exports.ADMIN_API_TOKEN = ADMIN_API_TOKEN;
var CPU_OVERHEAT_THRESHOLD = Number(process.env.CPU_OVERHEAT_THRESHOLD) || 80;
exports.CPU_OVERHEAT_THRESHOLD = CPU_OVERHEAT_THRESHOLD;
var JITSI_URL = (process.env.JITSI_URL === '') ? undefined : process.env.JITSI_URL;
exports.JITSI_URL = JITSI_URL;
var JITSI_ISS = process.env.JITSI_ISS || '';
exports.JITSI_ISS = JITSI_ISS;
var SECRET_JITSI_KEY = process.env.SECRET_JITSI_KEY || '';
exports.SECRET_JITSI_KEY = SECRET_JITSI_KEY;
var HTTP_PORT = parseInt(process.env.HTTP_PORT || '8080') || 8080;
exports.HTTP_PORT = HTTP_PORT;
var GRPC_PORT = parseInt(process.env.GRPC_PORT || '50051') || 50051;
exports.GRPC_PORT = GRPC_PORT;
exports.SOCKET_IDLE_TIMER = parseInt(process.env.SOCKET_IDLE_TIMER) || 30; // maximum time (in second) without activity before a socket is closed
exports.TURN_STATIC_AUTH_SECRET = process.env.TURN_STATIC_AUTH_SECRET || '';
